#!/usr/bin/env ruby

# note: this doesn't do any validation, has no error handling, etc
require 'rss'

if not ARGV[0]
  STDERR.puts "please provide a link to an atom feed" 
  exit 1
end

puts "# Actually Simple Syndication - https://tilde.town/~dzwdz/ass/"
puts "# generated by atom2ass.rb"

rss = RSS::Parser.parse(ARGV[0], false)
case rss.feed_type
when 'atom'
  rss.items.each do |item|
    puts "#{item.updated.content}\t#{item.link.href}\t#{item.title.content}"
  end
else
  STDERR.puts "unsupported feed type"
end
